### ISSUE TITLE
requests module with alpine image

### ISSUE THREAD

**Issue by flaiker** [jfilak/sapcli#10]
Hi Jakub,

I am currently trying to set up sapcli on GitLab to run unit tests on a test system every time a master build is triggered. This is my gitlab-ci.yml:

```yaml
abapunit:
  image: python:3-alpine
  stage: unittest
  variables:
    SAP_ASHOST: '****'
    SAP_CLIENT: '***'
    SAP_PORT: '***'
  before_script:
    - apk add --no-cache git py3-requests py3-openssl
    - git clone https://github.com/jfilak/sapcli.git
  script:
    - ./sapcli/sapcli
        --ashost $SAP_ASHOST
        --client $SAP_CLIENT
        --no-ssl
        --port $SAP_PORT
        --user $SAP_USER
        --password $SAP_PASSWORD
        aunit run package "/abc/def"
        --output junit4 > report.xml && cat report.xml
  artifacts:
    reports:
      junit: report.xml
```
Output:
```
$ apk add --no-cache git py3-requests py3-openssl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/16) Installing nghttp2-libs (1.38.0-r0)
(2/16) Installing libcurl (7.65.1-r0)
(3/16) Installing pcre2 (10.33-r0)
(4/16) Installing git (2.22.0-r0)
(5/16) Installing python3 (3.7.3-r0)
(6/16) Installing py3-cparser (2.19-r2)
(7/16) Installing py3-cffi (1.11.5-r4)
(8/16) Installing py3-idna (2.8-r1)
(9/16) Installing py3-asn1crypto (0.24.0-r1)
(10/16) Installing py3-six (1.12.0-r1)
(11/16) Installing py3-cryptography (2.6.1-r1)
(12/16) Installing py3-openssl (19.0.0-r0)
(13/16) Installing py3-chardet (3.0.4-r1)
(14/16) Installing py3-certifi (2019.6.16-r0)
(15/16) Installing py3-urllib3 (1.25.3-r0)
(16/16) Installing py3-requests (2.21.0-r4)
Executing busybox-1.30.1-r2.trigger
OK: 97 MiB in 51 packages
$ git clone https://github.com/jfilak/sapcli.git
Cloning into 'sapcli'...
$ ./sapcli/sapcli --ashost $SAP_ASHOST --client $SAP_CLIENT --no-ssl --port $SAP_PORT --user $SAP_USER --password $SAP_PASSWORD aunit run package "*****" --output junit4 > report.xml && cat report.xml
Traceback (most recent call last):
  File "./sapcli/sapcli", line 20, in <module>
    spec.loader.exec_module(sapcli)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/builds/*****/sapcli/bin/sapcli", line 14, in <module>
    import sap.adt
  File "/builds/****/sapcli/sap/adt/__init__.py", line 3, in <module>
    from sap.adt.core import Connection  # noqa: F401
  File "/builds/****/sapcli/sap/adt/core.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Uploading artifacts...
report.xml: found 1 matching files                 
Uploading artifacts to coordinator... ok            id=189 responseStatus=201 Created token=fFMjy5-c
ERROR: Job failed: exit code 1
```

It seems like the py3-requests package is not the one I need or is not included correctly. Any idea?

I tried Ubuntu at first which didn't show any syntax error but took minutes to run so I wanted to try the alpine image instead.

**Comment by flaiker** [comment]
I changed the method to install requests from apk to pip. That worked.
```yaml
    - pip3 install requests
    - apk add --no-cache git
```

No tests are executed though, hmm....
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="/ABC/DEF">
</testsuites>
```

**Comment by flaiker** [comment]
I think the backend version required might be higher than the one I have. At least the ABAP Unit run in ADT in the Http Trace looks quite different than the request sapcli makes. And in SMICM I can see the response that no tests were found for the selection criteria.

**Comment by jfilak** [comment]
Hi Fabian, how can I support you on your quest? I test sapcli on ABAP Platform 7.51 and higher. You definitely need ADT. If you can run unit tests from eclipse, you can capture communication log and we can enhance sapcli to support also your version of ABAP Platform.

**Comment by flaiker** [comment]
The information that it works on >= 7.51 already helps me because now I can test and see how it works on the 7.52 dev edition.

I'll report back to you!

**Comment by filak-sap** [comment]
BTW: you can replace `> report.xml && cat report.xml` with `| tee report.xml`.

**Comment by flaiker** [comment]
I'm back at it again. I'll open a new issue.
